run:
  concurrency: 4
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  go: '1.22'

linters:
  enable:
  - staticcheck
  - gosimple
  - ineffassign
  - typecheck
  - govet
  - unused
  - structcheck
  - varcheck
  - deadcode
  - stylecheck
  - gosec
  - interfacer
  - unconvert
  - gocyclo
  - misspell
  - unparam
  - scopelint
  - gocritic
  - golint
  - asciicheck
  - bodyclose
