run:
  concurrency: 4
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  go: '1.22'

linters:
  enable:
  - staticcheck
  - gosimple
  - ineffassign
  - typecheck
  - govet
  - unused
  - stylecheck
  - gosec
  - unconvert
  - gocyclo
  - misspell
  - unparam
  - gocritic
  - asciicheck
  - bodyclose
