// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: email.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (
  email
) VALUES (
  $1
)
`

func (q *Queries) AddUser(ctx context.Context, email pgtype.Text) error {
	_, err := q.db.Exec(ctx, addUser, email)
	return err
}
