// Code generated by mockery v2.43.2. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// mockEmailSender is an autogenerated mock type for the emailSender type
type mockEmailSender struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: to, message
func (_m *mockEmailSender) SendEmail(to string, message string) error {
	ret := _m.Called(to, message)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockEmailSender creates a new instance of mockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEmailSender {
	mock := &mockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
