// Code generated by mockery v2.43.2. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// mockCurrencyConverter is an autogenerated mock type for the currencyConverter type
type mockCurrencyConverter struct {
	mock.Mock
}

// GetUAHToUSD provides a mock function with given fields:
func (_m *mockCurrencyConverter) GetUAHToUSD() (float32, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUAHToUSD")
	}

	var r0 float32
	var r1 error
	if rf, ok := ret.Get(0).(func() (float32, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float32)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockCurrencyConverter creates a new instance of mockCurrencyConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCurrencyConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCurrencyConverter {
	mock := &mockCurrencyConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
