// Code generated by mockery v2.43.2. DO NOT EDIT.

package email

import (
	mock "github.com/stretchr/testify/mock"
	mail "gopkg.in/mail.v2"
)

// mockDialer is an autogenerated mock type for the dialer type
type mockDialer struct {
	mock.Mock
}

// DialAndSend provides a mock function with given fields: _a0
func (_m *mockDialer) DialAndSend(_a0 ...*mail.Message) error {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DialAndSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...*mail.Message) error); ok {
		r0 = rf(_a0...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockDialer creates a new instance of mockDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDialer {
	mock := &mockDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
