// Code generated by mockery v2.43.2. DO NOT EDIT.

package transport

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockEmailService is an autogenerated mock type for the emailService type
type mockEmailService struct {
	mock.Mock
}

// AddEmail provides a mock function with given fields: ctx, email
func (_m *mockEmailService) AddEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for AddEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockEmailService creates a new instance of mockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEmailService {
	mock := &mockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
